language: php


php:
    - 7.2


jobs:
    include:
        -   stage: Code Standard Check

            install:
                - travis_retry make code-checker-install
                - travis_retry make coding-standard-install
                - travis_retry make phpstan-install

            script:
                - make code-checker-run
                - make coding-standard-run
                - make phpstan-run


sudo: false


cache:
    directories:
        - $HOME/.composer/cache


notifications:
    email: false
