language: php

php:
    - 7.2

jobs:
    include:
        - stage: Coding Standard
          install:
              - travis_retry make code-checker-install
              - travis_retry make coding-standard-install
          script:
              - make code-checker-run
              - make coding-standard-run

        - stage: Static Analysis
          install:
              - travis_retry make phpstan-install
          script:
              - make phpstan-run

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
