language: php

services:
    - docker

before_install:
    - make travis-download-docker-compose
    - rm docker-compose.override.yml

jobs:
    include:
        - stage: Coding Standard
          install:
              - travis_retry make code-checker-install
              - travis_retry make coding-standard-install
          script:
              - make code-checker-run
              - make coding-standard-run

        - stage: Static Analysis
          install:
              - travis_retry make phpstan-install
          script:
              - make phpstan-run

        - stage: Tests
          install:
              - travis_retry make coverage-install
          script:
              - make coverage-run
          after_failure:
              - make tests-print
          after_script:
              - travis_retry make coverage-publish TRAVIS=1

sudo: required

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
