version: '3'

services:
    web:
        build: ./docker/php
        ports:
            - 80
            - 443
        volumes:
            - ./:/var/www/html

    node:
        image: node:latest
        command: tail -f /dev/null
        volumes:
            - ./:/app
        working_dir: /app
