version: '3'

services:
    web:
        volumes:
            - ./:/var/www/html:cached
            - ./docker/apache/localhost:/etc/apache2/sites-enabled
            - ~/nginx-proxy/certs:/etc/apache2/ssl
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        environment:
            VIRTUAL_HOST: www.harmim.localhost.com
            PHP_IDE_CONFIG: serverName=www.harmim.localhost.com
            DH_DEBUG: 1
            XDEBUG_CONFIG: remote_host=docker.for.mac.localhost

networks:
    default:
        external:
            name: nginx-proxy
